### PR TITLE
Fix: NFT card text wrap

### PR DESCRIPTION
**Pull request by pipemachine**
@CamArmstr- wasn't able to fully load the NFT previews as of creation of this PR. Strangely- this worked yesterday.
The intended functionality seems ok, but would be great to get a bit close to actual test cases with data loading. Any tips here?
Should be close on this one.

image

### CODE REVIEW

**Comment by pipemachine** [comment]
@CamArmstr- we should also decide ettiquette on `.gitignore` and `package.json`

**Comment by CamArmstr** [comment]
My guess is that 

> @CamArmstr- wasn't able to fully load the NFT previews as of creation of this PR. Strangely- this worked yesterday. The intended functionality seems ok, but would be great to get a bit close to actual test cases with data loading. Any tips here? Should be close on this one.
> 
> image

My guess is that there might be something up with your local NFTCardGrid component and how you named your dummy data. Maybe not all the data is making it into the prop? It looks like the title made it but not the NFT ID or the img link.

If that doesn't solve it, if you can share the code for that component I can help look through. NFTCardGrid is the gnarliest component in the app

**Comment by CamArmstr** [comment]
Yes absolutely. If you can get that as well that would be awesome

**Comment by pipemachine** [comment]
Ok good steps to getting the card dialed in.
image
image

**Pull request merged**
